"""empty message

Revision ID: 6233d358b91b
Revises: c6ea3d79d7bc
Create Date: 2019-02-21 17:22:32.486304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6233d358b91b'
down_revision = 'c6ea3d79d7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastStatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastStatus')
    # ### end Alembic commands ###
